#!/usr/bin/env python

import sys

infile = sys.argv[1]
outfile = sys.argv[2]

with open(infile) as fin:
    with open(outfile, 'w') as fout:
        for line in fin:
            fout.write('try:\n')
            fout.write('    ' + line)
            fout.write('except ImportError as err:\n')
            fout.write('    print(err)\n')

