#!/usr/bin/env python
import sys

infile = sys.argv[1]
outfile = sys.argv[2]

with open(infile) as fin:
    with open(outfile, 'w') as fout:
        fout.write('from contextlib import suppress\n')
        for line in fin:
            fout.write('with suppress(ImportError, ModuleNotFoundError):\n')
            fout.write('    ' + line)
